### PR TITLE
fix: Use https for authentication (#80)

### PR DESCRIPTION
**Pull request by bagage**
It looks like the fix is quite trivial actually :). Would you mind testing it (I am not much confident with technologies you used here)? 

If this is fixing the issue even in release mode, it would be really cool to have an update of the store version (so that I can upload hundreds of pending items :-D).

### CODE REVIEW

**Comment by bagage** [comment]
Up :).

**Comment by loicortola** [comment]
Hi, @bagage 

thanks a lot for the PR! :)
I will test tomorrow, there is only one thing I need to make sure works:
Whether Android fully supports Let'sEncrypt SSL Root in their OS or not.
I think it should be fine.

Have you tested your code?

**Comment by bagage** [comment]
I've tested with the test server and it went just fine; but I didn't test with real production server… because I didn't found how :).

**Comment by bagage** [comment]
@loicortola any update? Thrilled to reuse osm contributor 😂.

**Comment by loicortola** [comment]
Went just fine! Thanks a lot for the PR.
Will make a release ASAP

**Pull request merged**
